version: '3.8'

services: 
  doctor-app:
    image: deploy-doctor-app:latest
    restart: always
    environment:
      - HOSTNAME=0.0.0.0
    ports:
      - target: 8080
        published: 3030
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
        reservations:
          cpus: '0.5'
          memory: '256M'
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://0.0.0.0:8080/health/live"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
